server:
  port: 8181

app:
  aws:
    bucket:
      name: 'com.kallepaulsson.photobackup'
  backup:
    paths:
      base_path: /home/kalle/tmp
      photos_path: ${app.backup.paths.base_path}/Photos
      backup_path: ${app.backup.paths.base_path}/backup
