app:
  aws:
    bucket:
      name: 'com.kallepaulsson.photobackup'
  backup:
    paths:
      base_path: /home/kalle/tmp
      photos_path: ${app.backup.paths.base_path}/photos
      monthly_path: ${app.backup.paths.base_path}/monthly
      aws_path: ${app.backup.paths.base_path}/aws
